### ISSUE TITLE
Please add URI to credentials.yml for Springboot app support

### ISSUE THREAD

**Issue by cwb124** [blacksmith-community/rabbitmq-forge-boshrelease#2]
To use the Rabbitmq connector, Springboot apps require a URI parsed from known values.  The data that connector will check for is defined here:  https://cloud.spring.io/spring-cloud-connectors/spring-cloud-cloud-foundry-connector.html#_rabbitmq

The uri key:value should be formatted as such:  

`"uri": "amqp://username:password@host_ip:port/service_instance_name"`

It is better for the uri to be defined on the fly rather than have the user create the variables so the apps are portable across CF deployments that may not have all their services named uniformly.

URI needs to be added in two places:

jobs/rabbitmq-blacksmith-plans/templates/plans/standalone/credentials.yml
jobs/rabbitmq-blacksmith-plans/templates/plans/cluster/credentials.yml

**Comment by cwb124** [comment]
So we have created most of the URI parameter but we are stuck on how to create/provide the instance_name/instance_ID at the end of the URI:

What we have to far:
`uri: (( concat "amqp://" meta.username ":" meta.password "@" jobs.standalone/0.ips[0] ":" credentials.rmq_port ))`

We need to append a service_name or service_id to the end after rmq_port.  But I'm not sure how to do that as it doesn't seem that instance_id/name is not currently a part of the rabbitmq forge release at this time.

**Comment by jhunt** [comment]
In this context, I believe `service_instance_name` is just the RabbitMQ vhost.  Have you tried leaving it off? i.e.:

```
uri: (( concat "amqp://" meta.username ":" meta.password "@" jobs.standalone/0.ips[0] ":" credentials.rmq_port "/" ))
```

**Comment by cwb124** [comment]
Ok let me try that and see how the app responds.

**Comment by cwb124** [comment]
Please add:  uri: (( concat "amqp://" meta.username ":" meta.password "@" jobs.standalone/0.ips[0] ":" credentials.rmq_port ))

to the jobs/rabbitmq-blacksmith-plans/templates/plans/standalone/credentials.yml.  

Will worry about the cluster stuff later.  Thanks!

**Comment by jhunt** [comment]
I'll be taking a look at this this upcoming week.

**Comment by jhunt** [comment]
Out of curiosity, @cwb124, what happens if you use the default vhost '/', URI-encoded?

i.e.:

```
uri: (( concat "amqp://" meta.username ":" meta.password "@" jobs.standalone/0.ips[0] ":" credentials.rmq_port "/%2f" ))
```

**Comment by jhunt** [comment]
@cwb124 any update?

**Comment by cwb124** [comment]
Sorry about that.  Missed this request.  Here is the line we fixed in our fork that works for the credentials.yml in standalone plans.

uri: amqp://(( grab meta.username )):(( grab meta.password ))@(( grab jobs.standalone/0.ips[0] )):5672/(( grab meta.instance_name ))

**Comment by jhunt** [comment]
Okay, so on PR #3, we're going to have to account for that `/(( grab meta.instance_name ))` in the cartesian product call.

**Comment by jhunt** [comment]
Ah,  I see `meta.instance_name` isn't a thing any more.  I think that means we can merge #3.
